version: "3.1"
services:
  api:
    image: webdev_api
    volumes:
     - ./backend:/usr/src/webdev
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: mysql://root:apple1@db/web_dev
    #cargo run needed for dev build
    command: cargo run --bin web_dev   

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: apple1
      MYSQL_DATABASE: web_dev

  frontend:
    image: webdev_frontend
    ports:
      - "80:80"

