[package]
name = "hello_macro_main"
version = "0.1.0"
authors = ["kluzynick"]
edition = "2018"

[dependencies]
hello_macro = { path = "../hello_macro" }
hello_macro_derive = { path = "../hello_macro_derive" }
